In [13]:
# First, install the required spaCy model
import sys
import subprocess
subprocess.check_call([sys.executable, "-m", "pip", "install", "spacy"])
subprocess.check_call([sys.executable, "-m", "spacy", "download", "en_core_web_sm"])

# Then load the model
import spacy
import pandas as pd
nlp = spacy.load('en_core_web_sm')

In [14]:
nlp

In [15]:
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the b est blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex he r she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her s isters marriage been mistress of his house from a very early period her mother had died too long ago for her to hav e more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as gove rness who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses fami ly less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away th ey had been living together as friend and friend very mutually attached and emma doing just what she liked highly e steeming miss taylors judgment but directed chiefly by her own"

In [16]:
spacy_doc = nlp(emma_ja)

In [45]:
rows = []
for token in spacy_doc:
    rows.append({
        "token": token.text,              # the actual word
        "pos": token.pos_,                # coarse POS tag (NOUN, VERB, etc.)
        "pos_detail": token.tag_,         # fine-grained POS tag
        "pos_explained": spacy.explain(token.pos_),  # human-readable description
        "dep": token.dep_,                # syntactic dependency (subject, object, etc.)
        "head": token.head.text           # the head word this token depends on
    })

# Convert list of dicts into a DataFrame
pos_df = pd.DataFrame(rows)

print(pos_df)

         token    pos pos_detail             pos_explained     dep       head
0         emma  PROPN        NNP               proper noun   nsubj  woodhouse
1    woodhouse  PROPN        NNP               proper noun   nsubj     seemed
2     handsome    ADJ         JJ                 adjective    amod     clever
3       clever    ADJ         JJ                 adjective  advmod  woodhouse
4          and  CCONJ         CC  coordinating conjunction      cc     clever
..         ...    ...        ...                       ...     ...        ...
217   directed   VERB        VBD                      verb    conj      liked
218    chiefly    ADV         RB                    adverb  advmod   directed
219         by    ADP         IN                adposition   agent   directed
220        her   PRON       PRP$                   pronoun    poss        own
221        own    ADJ         JJ                 adjective    pobj         by

[222 rows x 6 columns]

In [48]:
pos_df[:10]

,token,pos,pos_detail,pos_explained,dep,head
0,emma,PROPN,NNP,proper noun,nsubj,woodhouse
1,woodhouse,PROPN,NNP,proper noun,nsubj,seemed
2,handsome,ADJ,JJ,adjective,amod,clever
3,clever,ADJ,JJ,adjective,advmod,woodhouse
4,and,CCONJ,CC,coordinating conjunction,cc,clever
5,rich,ADJ,JJ,adjective,conj,clever
6,with,ADP,IN,adposition,prep,rich
7,a,DET,DT,determiner,det,disposition
8,comfortable,ADJ,JJ,adjective,amod,home
9,home,NOUN,NN,noun,nmod,disposition

In [23]:
rows = []
for token in spacy_doc:
    rows.append({
        "token": token.text,              # the actual word
        "pos": token.pos_,                # coarse POS tag (NOUN, VERB, etc.)
        
    })

# Convert list of dicts into a DataFrame
pos_df = pd.DataFrame(rows)

print(pos_df)

         token    pos
0         emma  PROPN
1    woodhouse  PROPN
2     handsome    ADJ
3       clever    ADJ
4          and  CCONJ
..         ...    ...
217   directed   VERB
218    chiefly    ADV
219         by    ADP
220        her   PRON
221        own    ADJ

[222 rows x 2 columns]

In [21]:
pos_df.head(5)

       token    pos pos_detail             pos_explained     dep       head
0       emma  PROPN        NNP               proper noun   nsubj  woodhouse
1  woodhouse  PROPN        NNP               proper noun   nsubj     seemed
2   handsome    ADJ         JJ                 adjective    amod     clever
3     clever    ADJ         JJ                 adjective  advmod  woodhouse
4        and  CCONJ         CC  coordinating conjunction      cc     clever

In [30]:
pos_df_counts = pos_df.groupby(['token', 'pos']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)

In [31]:
pos_df_counts.head(10)

    token    pos  counts
95     of    ADP      14
53    had    AUX       8
6     and  CCONJ       8
60    her   PRON       8
123   the    DET       8
0       a    DET       6
125    to   PART       5
67     in    ADP       4
14   been    AUX       4
131  very    ADV       4

In [49]:
pos_df_counts = pos_df.groupby(['token', 'pos']).size().reset_index(name='counts').sort_values(by='counts')

In [50]:
pos_df_counts.head(10)

            token    pos  counts
71         isters   NOUN       1
100        passed   VERB       1
99   particularly    ADV       1
98            own    ADJ       1
97             or  CCONJ       1
96         office   NOUN       1
94            now    ADV       1
93        nominal    ADJ       1
92         nearly    ADV       1
91       mutually    ADV       1

In [51]:

pos_df_poscounts = pos_df_counts.groupby(['pos'])['token'].count().sort_values(ascending=False)
pos_df_poscounts.head(10)

pos
NOUN     38
VERB     20
ADJ      18
ADV      17
PRON     10
ADP       9
PROPN     8
DET       5
AUX       4
CCONJ     3
Name: token, dtype: int64

In [41]:

nouns = pos_df_counts[pos_df_counts.pos == 'NOUN'][:10]
nouns

        token   pos  counts
71     isters  NOUN       1
96     office  NOUN       1
86   mistress  NOUN       1
84       miss  NOUN       1
101    period  NOUN       1
83   mildness  NOUN       1
73   judgment  NOUN       1
70   intimacy  NOUN       1
65      house  NOUN       1
82   marriage  NOUN       1

In [42]:

nouns = pos_df_counts[pos_df_counts.pos == 'NOUN'][:10] 
nouns

        token   pos  counts
71     isters  NOUN       1
96     office  NOUN       1
86   mistress  NOUN       1
84       miss  NOUN       1
101    period  NOUN       1
83   mildness  NOUN       1
73   judgment  NOUN       1
70   intimacy  NOUN       1
65      house  NOUN       1
82   marriage  NOUN       1